apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  namespace: artyom-test
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    envFrom:
    - secretRef:
        name: test-secret
    env:
      - name: SECOND_SECRET
        valueFrom:
          secretKeyRef:
            name: test-secret2
            key: SECOND_SECRET
