pipeline {
    
    agent any
    
    stages {
        stage('Pre-build') {
            steps {
                git branch: 'master',
                url: 'https://github.com/DevOps-DP-185/Identity.git'
                sh 'sudo mvn -f ./identity-starter/pom.xml clean install'
            }
        }   
        stage('Test') {
            steps{
                sh 'mvn --version'
                sh 'docker --version'
            }
        }
        stage('Build') {
            steps{
                git branch: 'master',
                url: 'https://github.com/DevOps-DP-185/Gateway.git'
                sh 'sudo mvn clean package'
            }
        }      
        stage('Package') {
            steps{
                sh 'sudo docker build -t artemkulish/zone3000:gateway .'
            }
        }   
        stage('Deliver') {
            steps {
               sh 'sudo docker push artemkulish/zone3000:gateway'
            }   
        } 
        stage('Cleanup') {
            steps {
               sh 'sudo docker image prune -a -f | grep Total'
            }   
        } 
    }    
}
