pipeline {
    agent {
        docker { image 'maven:3-alpine' }
    }
    
    stages {
        stage('Checkout') {
            steps {
                git branch: 'master',
                url: 'https://github.com/Artemkulish/kulya.git'

                sh "ls -lat"
            }
        }   
        stage('Test') {
            steps {
                sh 'mvn --version'   
            }
        }
    }
}
