- name: Upload a file
  hosts: haproxy
  become: yes
  tasks:  
  - name: Modify conf file
    shell: |
       echo 'cat >> /etc/haproxy/haproxy.cfg <<EOL
       frontend http_front
                bind *:80
                default_backend http_back
                
       frontend https_front
                bind *:443
                default_backend https_back
                
       backend http_back
               balance roundrobin
               server myweb1 172.31.47.134:80 weight 55
              server myweb1 172.31.46.99:80  weight 45
               
       backend https_back
               balance roundrobin
               server myweb1 172.31.47.134:443
               server myweb1 172.31.46.99:443
       EOL' | sudo -s
  - name: Restart Haproxy
    service: name=haproxy state=restarted
