- name: Configure LoadBalancer
  hosts: haproxy
  become: yes
  vars:
     source_file: /home/ssl/svagworks/2.pem
     destin_file: /etc/ssl

  tasks:  
  - name: Copy SSL in the PEM format to Haproxy
    copy: srs={{ source_file }} dest={{ destin_file }}
    
  - name: Modify Haproxy conf file
    shell: |
       echo 'cat >> /etc/haproxy/haproxy.cfg <<EOL
       frontend http_https
                bind *:80
                bind *:443 ssl crt /etc/ssl/2.pem
                redirect scheme https if !{ ssl_fc }
                default_backend nodes
                
       backend nodes
               balance roundrobin
               server myweb1 172.31.47.134:80 weight 55
               server myweb2 172.31.46.99:80  weight 45
               
       EOL' | sudo -s
  - name: Restart Haproxy
    service: name=haproxy state=restarted
