name: Test Json

on: push

env:
  apps: 'agent server'

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - id: set_matrix
        run: |
          apps=(${{ env.apps }})
          start_array="["
          end_array="]"
          result=""

          for app in ${apps[@]}
          do
            result+="'${app}',"
          done

          matrix=$start$result$end
          echo "::set-output name=matrix::$matrix"
    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}
      

  test:
    strategy:
      matrix:
        version: ${{fromJson('["agent", "server"]')}}
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: test
        run: echo ${{ matrix.version }}
