name: Test Json

on: push

env:
  apps: 'agent'

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - id: set_matrix
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
