name: Test Json

on: push

jobs:
  test:
    strategy:
      matrix:
        version: ['1', '2', '3',]
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo ${{ matrix.version }}
